// 远端工具 pi stub 生成（ADR-0033 / R-5）：注册表条目（R-1：{name,argsSchema,remote}）→ pi 扩展声明
// 的工具。argsSchema 由本仓可序列化 schema.ts 桥接到 pi 侧 TypeBox；handler = 经本地桥发起转发
// （读 env：AGENTANY_BRIDGE_URL/NONCE/RUN_ID），**不含任何本地执行逻辑**。
// 生成物 = 一个 .ts 扩展文件（-e 注入），run 期叠加在 wf.extensions 之上（ctxFor 拼接）。
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { stubDirs } from "../config";
import type { Schema } from "@agentany/ws-protocol"; // ADR-0034 D2：argsSchema 类型真相在协议包

// —— schema.ts → TypeBox 桥（R-5 决策：stub 的参数筛查与本地工具一致）——
// 注意：本模块**不在** pi 进程内 import typebox（那是扩展产物做的事）；这里只产出含 typebox 调用的代码文本。
export function schemaToTypeBox(s: Schema, indent = "    "): string {
  switch (s._t) {
    case "any":
      return "Type.Any()";
    case "string":
      return "Type.String()";
    case "number":
      return "Type.Number()";
    case "boolean":
      return "Type.Boolean()";
    case "enum":
      return `Type.Union([${(s.vals as unknown[]).map((v) => `Type.Literal(${JSON.stringify(v)})`).join(", ")}])`;
    case "optional":
      return `Type.Optional(${schemaToTypeBox(s.inner as Schema, indent)})`;
    case "array":
      return `Type.Array(${schemaToTypeBox(s.inner as Schema, indent)})`;
    case "object": {
      const shape = s.shape as Record<string, Schema>;
      const body = Object.entries(shape)
        .map(([k, v]) => `${indent}  ${JSON.stringify(k)}: ${schemaToTypeBox(v, indent + "    ")},`)
        .join("\n");
      return `Type.Object({\n${body}\n${indent}})`; // 顶层 object 压平 indent（调用方自行控制）
    }
    default:
      return "Type.Any()";
  }
}

const STUB_TEMPLATE = (toolName: string, piName: string, typeboxParams: string): string => `// AUTO-GENERATED by agentany ADR-0033 R-5（远端工具 stub；勿手改）。
// handler = 转发调用（env 读 bridge 坐标 + runId）；无本地执行逻辑。
// pi 注册名 = 净化名（OpenAI 兼容 API function.name 须 ^[a-zA-Z0-9_-]+$，带点原名 400——2026-08-21 真机验收实测）；
// 桥转发仍用注册表原名（桥按原名查表路由）。
import type { ExtensionAPI, AgentToolResult } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

async function forwardBridge(tool: string, args: unknown): Promise<{ ok: boolean; text: string }> {
  const url = process.env.AGENTANY_BRIDGE_URL;
  const nonce = process.env.AGENTANY_BRIDGE_NONCE;
  const runId = process.env.AGENTANY_RUN_ID;
  if (!url || !nonce || !runId) return { ok: false, text: "tool " + tool + ": bridge 环境缺失（AGENTANY_BRIDGE_URL/NONCE/RUN_ID）" };
  const r = await fetch(url + "/run/remote-tool", {
    method: "POST",
    headers: { authorization: "Bearer " + nonce, "content-type": "application/json" },
    body: JSON.stringify({ runId, tool, args: args ?? {} }),
  });
  const body = (await r.json().catch(() => ({}))) as any;
  // tool_result 摘要（失败带 isError=true：错误/原因直达 LLM，agentic loop 可据此重试/止损）
  return body?.ok
    ? { ok: true, text: body.stdout ?? "tool completed" }
    : { ok: false, text: "tool " + tool + " 失败: " + (body?.error ?? body?.stderr ?? r.status) };
}

export default function remoteTools(pi: ExtensionAPI) {
  pi.registerTool({
    name: ${JSON.stringify(piName)},
    label: ${JSON.stringify(toolName)},
    description: ${JSON.stringify(`远端工具（ADR-0033/R-5）：转发到在线设备执行，结果回传。` + toolName)},
    promptSnippet: ${JSON.stringify(`Remote device tool: ${toolName}`)},
    parameters: ${typeboxParams},
    executionMode: "sequential",
    async execute(_id: string, params: Record<string, unknown>): Promise<AgentToolResult> {
      const call = await forwardBridge(${JSON.stringify(toolName)}, params);
      return { content: [{ type: "text", text: call.text }], isError: !call.ok };
    },
  });
}
`;

/** 生成一条工具对应的 stub 扩展文件 → 返回绝对路径（per-run per-tool 唯一：文件名带工具名，多 remote 工具互不覆写）。 */
export function writeStubExtension(toolName: string, argsSchema: Schema, runId: string): string {
  const safe = toolName.replace(/[^A-Za-z0-9_-]/g, "_"); // pi 注册名/文件名安全（工具名限 registry 名）
  const content = STUB_TEMPLATE(toolName, safe, schemaToTypeBox(argsSchema).replace(/^\s{4}/, ""));
  const dir = stubDirs();
  mkdirSync(dir, { recursive: true });
  const path = join(dir, `remote-${runId.slice(0, 12)}-${safe}.ts`);
  writeFileSync(path, content);
  return path;
}